### ISSUE TITLE
Add travis ci?

### ISSUE THREAD

**Issue by bpbond** [JGCRI/gcammaptools#1]
Hey @rplzzz want me to add continuous integration to the repo?

**Comment by rplzzz** [comment]
Sure, that would be fantastic.  I had been planning to look into it, but I have a few other things higher on the to-do list.

**Comment by bpbond** [comment]
Hmm, I'm having trouble building the `proj4` package (a dependency of `ggalt`) on Debian. Have you built gcammaptools on Linux?

https://travis-ci.org/JGCRI/gcammaptools

**Comment by rplzzz** [comment]
No, I haven't tried it on linux yet.  I'll look into it if I have some time today, but I'm going to take a blind guess that your problem is with the gfortran libraries.  Everything else in that package should be straightforward.

**Comment by bpbond** [comment]
OK, we can revisit this. As I note in #4 , for now I've used the `r_binary_packages` options to install `proj4`, because that's so easy, but installing it from source is probably the way to go. Later.
