### ISSUE TITLE
API for map plotting needs refactoring

### ISSUE THREAD

**Issue by rplzzz** [JGCRI/gcammaptools#16]
Right now the gcammaptools API takes a monolithic approach to specifying plots.  For example, `plot_GCAM` sets the aesthetics, draws the graticule, draws the base map, colors the map if necessary, sets the color sale, applies the map projection, and sets theme elements.  Bundling all that functionality into a single function makes it hard to reuse any of this functionality.  For example, `plot_GCAM_grid` uses `plot_GCAM` to draw its base map, but this causes some problems with the legend title that have to be worked around, and fine-tuning the color scale is likely to be a major hassle.

What we need is a set of customized ggplot elements that we can chain together according to ggplot conventions, so we could write something like
```
plot <- gcam_basemap(...) + gcam_grid(...) + gcam_colorscale(...) + gcam_theme(...)
```
Each one of those could provide a set of sensible defaults to narrow down the range of options and provide a consistent house style for geographic plots, while still allowing us to remix as required.

**Comment by bpbond** [comment]
Note ggplot2 now has an official extension mechanism: https://cran.r-project.org/web/packages/ggplot2/vignettes/extending-ggplot2.html

**Comment by rplzzz** [comment]
Yes, we sort of use that mechanism, but we don't exactly use it the way it was intended (e.g., combining plotting and theme functionality in the same function).
