### ISSUE TITLE
Common utility for transforming data 

### ISSUE THREAD

**Issue by cahartin** [JGCRI/gcammaptools#18]
It would be a useful utility to map differences between scenarios within the function rather than switching between wide and long dataframe formats.

**Comment by rplzzz** [comment]
@cahartin I feel like we talked about this idea, and it made sense at the time, but at this point I can't remember what function we were referring to.  Do you remember it?

**Comment by cahartin** [comment]
It wasn't in reference to a particular function.  It would be a good if we could call a function that would produce a difference field between 2 scenarios, with the result still in the wide format (years as column names) to easily plot using `plot_GCAM`

**Comment by rplzzz** [comment]
Right.  That actually sounds like a better fit for [rgcam](https://github.com/JGCRI/rgcam) than for this package.  Maybe I'll crank that out while I'm thinking about some stuff on another project.

**Comment by crvernon** [comment]
Version 2 is in development and will have functionality to only create a set of maps that work every time or provide a reason of why they are not working.  These maps will be produced using as little GIS processing as possible to make them efficient and stable.
