### ISSUE TITLE
Documentation links not working

### ISSUE THREAD

**Issue by bpbond** [JGCRI/gcammaptools#2]
A number of documentation links don't work, i.e. `devtools::check()` is reporting errors on them. I'm about to open a PR that changes them (for now) to just `\code{}`, i.e. removes the links, because I want to make sure the package passes `R CMD CHECK` for #1 . They include

* `\code{\link{mapproj::coord_map}}` in `diag_header`:43
* `\code{\link{map.usa}}` in `gcammaptools`:36
* `\code{\link{ggalt::coord_proj}}` and  in `Map_Functions`:49
* `\code{\link{mapproj::coord_map}}` in `Map_Functions`:440

**Comment by rplzzz** [comment]
That's not too surprising, since `map.usa` doesn't exist yet.  I need to dig up the shapefile for GCAM-USA somewhere.  For the others, it appears that you can't link to the documentation for a function in another package (or if you can do it, the way I tried to do it isn't the right way).

**Comment by rplzzz** [comment]
BTW, I figured out how to link to documentation in other packages.  You write `\link[package]{function}`.  When I get a chance I'll go back and fix the broken links identified here.
