### ISSUE TITLE
Fix warnings in package check

### ISSUE THREAD

**Issue by rplzzz** [JGCRI/gcammaptools#22]
Right now the package check stage throws several warnings on the `alter-proj4-method` branch.  I've disabled warnings_are_errors on the CI for that branch, but ultimately the package needs to pass checks with no warnings.

**Comment by crvernon** [comment]
Caleb, these are the "quiet" ones we spoke of.

**Comment by calebbraun** [comment]
All of the warnings I've found have been the result of printing the map returned from `plot_GCAM()`. Because the warnings are generated when the map is drawn, I can't think of a way to suppress them within the actual package. Any ideas?

**Comment by rplzzz** [comment]
We don't want to just suppress the messages.  We need to figure out why the warnings are happening and fix them at their source.

**Comment by calebbraun** [comment]
The latest build passes and the branch deploys to shinyapps.io without problems.
