### ISSUE TITLE
Fix package vignette

### ISSUE THREAD

**Issue by rplzzz** [JGCRI/gcammaptools#23]
The examples vignette needs to be updated to work with the new changes on the `alter-proj4-method` branch.

**Comment by crvernon** [comment]
Caleb is working on now.

**Comment by calebbraun** [comment]
I've updated all of them except for the Winkel Tripel projection, which currently has a proj4 string that throws an error. I also replaced the sample data to a long form data set, as is now the standard rgcam output.
