### ISSUE TITLE
add_region_ID not working for basin235

### ISSUE THREAD

**Issue by nealtg** [JGCRI/gcammaptools#28]
After changing the water basin variable name to 'region' to allow for use of add_region_ID the following code:
```
groundwater <- add_region_ID(groundwater, lookupfile = basin235)
```
results in a data frame that is all 0's except for 'region' and 'id'. These two variables are also reversed, id values in the region variable and vis versa, which is likely causing add_region_ID to work incorrectly. 

Starting over and changing the water basin variable name to 'id' allows add_region_ID to work, but provides 'id' variables as water basin names rather than water basin numbers and 'region' as the water basin number as class character rather than numeric

**Comment by calebbraun** [comment]
Thanks for pointing this out. The order of region and id in the basin235 lookup file was reversed. I have pushed an updated file, so please let me know if you have further problems with this.

**Comment by nealtg** [comment]
Thank you for this fix. 

add_region_ID works correctly now for the basins which have consistent naming, however, add_region_ID results in only 147 matches as basin names within map.basin235 are currently different than output from GCAM. USA regions are defined as 'Great Lakes Basin' in map.basin235 but are output from GCAM as 'Great Lakes'. I am not sure if basin names are different across different pulls of GCAM

**Comment by calebbraun** [comment]
It is possible that older versions of GCAM could have different basin names, but in the most recent versions,  there is no basin just called 'Great Lakes'. Which version are you running?

**Comment by nealtg** [comment]
I am currently running feature/water-markets

**Comment by calebbraun** [comment]
We don't currently support the basin names in that feature, however you can match them to the ones we do support fairly easily. Using the file below, try the following:
```
altnames <- read.csv('alternate_basin_names.txt', stringsAsFactors = F)
groundwater<- merge(groundwater, altnames, by.x = 'region', by.y = 'basin.name', sort = F)
groundwater$region <- groundwater$region.name
groundwater$region.name <- NULL

groundwater <- add_region_ID(groundwater, lookupfile = basin235)
```

[alternate_basin_names.txt](https://github.com/JGCRI/gcammaptools/files/1479936/alternate_basin_names.txt)

**Comment by nealtg** [comment]
Thank you, this works well. Unless you see it necessary to remain open, this issue can be closed.
