### ISSUE TITLE
Border polygons stretched too much with certain projections

### ISSUE THREAD

**Issue by calebbraun** [JGCRI/gcammaptools#38]
`plot_GCAM(map.rgn32, proj_type = 'EPSG', proj = 4985)` gives:
![image](https://user-images.githubusercontent.com/12344924/35926957-80368ef0-0bf7-11e8-8847-c93558fcef0e.png)

**Comment by calebbraun** [comment]
With latest update, this now plots empty map with no error. We need to think about whether all projections can be supported, or how to indicate if some can't.

See also:
`plot_GCAM(map.rgn32, proj_type = 'EPSG', proj = 3395)`

**Comment by crvernon** [comment]
Version 2 is in development and will have functionality to only create a set of maps that work every time or provide a reason of why they are not working.  These maps will be produced using as little GIS processing as possible to make them efficient and stable. Stay tuned!
