### ISSUE TITLE
Travis-CI `warnings_are_errors` are set to false

### ISSUE THREAD

**Issue by bpbond** [JGCRI/gcammaptools#4]
This is NOT good, as warnings from `R CMD CHECK` are generally things you need to pay attention to and fix. But:

* `rgdal` wouldn't install on Travis via apt-get approach
* So I installed it via `r_binary_packages`
* But the binary is perhaps an old version? Anyway, the vignette wouldn't build b/c of some undefined symbol error in rgeos or rgdal
* So I added '--no-build-vignettes' to the R CMD CHECK and BUILD arguments
* But this resulted in a warning of no matching vignette html/pdf file
* So, I set `warnings_are_errors: false`

At some point, we'd like to revisit this--either figure out how to do a source rgdal installation; or include the vignette-build products in the repo I guess.

See commits in PR #3 for various .travis.yml changes I tried.

**Comment by rplzzz** [comment]
Ok, so I think rgdal and proj4 are having similar problems, which is that they both have certain libraries as "system requirements"  ([proj4 package summary](https://cran.r-project.org/web/packages/proj4/index.html), [rgdal package summary](https://cran.r-project.org/web/packages/rgdal/index.html)).  If you don't have those system libraries installed, then the package install will fail.  

So, what is the best practice regarding these system requirements?  One obvious fix would be to update the installation instructions to include installing these libraries as a first step.  Using binary packages is another I guess.  Neither seems entirely satisfactory.

**Comment by bpbond** [comment]
Right. No, neither is satisfactory! This issue is Linux-specific I think–you don't need to do extra installation on OS X, at least. For now, I guess just list those under `Imports:` and provide documentation about the build-vs-binary options available.

That said, I'm not sure what the best practice is here; this might be a good question to ask on [r-package-devel](https://stat.ethz.ch/mailman/listinfo/r-package-devel).

**Comment by rplzzz** [comment]
Fixed in dd5df07.
