### ISSUE TITLE
Raster data extends past map bounds

### ISSUE THREAD

**Issue by calebbraun** [JGCRI/gcammaptools#45]
The `plot_GCAM_grid` function crops raster data to the bounds of the map, but it is not exact. Cells that are mostly within bounds are still included which causes the edge of the plot to be pushed past the edge of the  map.

**Comment by crvernon** [comment]
Version 2 is in development and will have functionality to only create a set of maps that work every time or provide a reason of why they are not working.  These maps will be produced using as little GIS processing as possible to make them efficient and stable. Stay tuned!
