### ISSUE TITLE
Feature for coloring maps with no regional data

### ISSUE THREAD

**Issue by calebbraun** [JGCRI/gcammaptools#46]
Maybe we should let the map `FILL_COLOR` be an optional parameter of `plot_GCAM`. It shouldn't matter too much when plotting just to show region boundaries, but may affect the look of gridded data.

**Comment by crvernon** [comment]
Version 2 is in development and will have functionality to only create a set of maps that work every time or provide a reason of why they are not working.  These maps will be produced using as little GIS processing as possible to make them efficient and stable. Stay tuned!
