### ISSUE TITLE
Geojson shapefile for 32-region GCAM has distorted Antarctica

### ISSUE THREAD

**Issue by cledna** [JGCRI/gcammaptools#8]
I noticed that the Antarctica polygon for the 32-region GCAM shapefile is distorted at the bottom. This occurs in the Robinson, Eckert-III and Winkel-Tripel projections. I think it can be fixed by replacing the Antarctica polygon in the shapefile. I can work on this.  
![gcam32shapefile](https://cloud.githubusercontent.com/assets/14073494/21062760/3e4e0098-be20-11e6-9554-14be0850218a.png)

**Comment by rplzzz** [comment]
Yes, I noticed that too.  What is happening is that `geom_polygon` connects the last point of the polygon to the first point.  Evidently our last point has a latitude just a bit lower than the first one.  We could probably fix it by adding one last point at the same longitude as the last one and the same latitude as the first one (this is assuming the points in the shape are running from west to east).  That should cause the connector line to go across the bottom correctly.

We should also probably adjust the default extent for the world map.  Right now it goes from -90 to +90, which creates issues near the poles.  If we adjust it slightly in from the poles, say -88 to +88, that should make the Antarctica problem a little easier to fix.

**Comment by cledna** [comment]
I've submitted a pull request for this.
